version: "3.9"

services:
  app:
    build: .
    container_name: Vivo-Back
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://root:root@mongo:27017/test"
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: test
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
